<?php

$handle = fopen("colours.csv", "r");
$colours = array();
$maxLen = 0;
while ($line = fgetcsv($handle)) {
    $maxLen = $maxLen > strlen($line[0]) ? $maxLen : strlen($line[0]);
    $colours[] = $line;
}
fclose($handle);
$handle = null;

$handle = fopen('ColorTable.def.h', 'w');
fwrite($handle, <<<HEADER
//
//  ColorTable.h
//  goosdl
//
//  Created by Albert Varaksin on 18/03/2014.
//  Copyright (c) 2014 Albert Varaksin. All rights reserved.
//

/**
 * This table defines all named colours and their corresponding
 * RGB values. This is autogenerated from a colours csv table
 */
#define COLOR_TABLE(_)
HEADER
);
foreach($colours as $line) {
    $name  = ucfirst($line[0]);
    $red   = $line[1];
    $green = $line[2];
    $blue  = $line[3];
    
    $str = " \\\n    _( " . $name . "," . str_repeat(' ', $maxLen - strlen($name)) . " "
         . $red   . "," . str_repeat(' ', 3 - strlen($red))   . " "
         . $green . "," . str_repeat(' ', 3 - strlen($green)) . " "
         . $blue        . str_repeat(' ', 3 - strlen($blue))  . " )"
    ;
    
    fwrite($handle, $str);
}
fwrite($handle, "\n");
fflush($handle);
fclose($handle);
