//---------------------------------------------------------------------------
/// \file   version.hpp
/// \brief  Header file generated by CMake
//
// This file is part of Rhea.  Rhea is free software: you can redistribute
// it and/or modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation, either version 3
// of the License, or (at your option) any later version.
//
// Rhea is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
// more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Rhea.  If not, see <http://www.gnu.org/licenses/>.
//
// Copyright 2012, nocte@hippie.nu
//---------------------------------------------------------------------------
#pragma once

/** The library's version number as a dotted triplet string. */
#define RHEA_VERSION "0.1.2"

/** The library's major version number.
 *  This gets bumped whenever the API breaks. */
#define RHEA_VERSION_MAJOR "0"

/** The library's minor version number.
 *  This gets bumped whenever the API is extended. */
#define RHEA_VERSION_MINOR "1"

/** The library's patch number.
 *  This gets bumped for bug fixes and optimizations. */
#define RHEA_VERSION_PATCH "2"

